// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: core-service/core-service.proto

package core

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PromptRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Запрос пользователя
	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	// кол-во необходимых контекстов (рекомендуется 5)
	Limit         string `protobuf:"bytes,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromptRequest) Reset() {
	*x = PromptRequest{}
	mi := &file_core_service_core_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromptRequest) ProtoMessage() {}

func (x *PromptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_service_core_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromptRequest.ProtoReflect.Descriptor instead.
func (*PromptRequest) Descriptor() ([]byte, []int) {
	return file_core_service_core_service_proto_rawDescGZIP(), []int{0}
}

func (x *PromptRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *PromptRequest) GetLimit() string {
	if x != nil {
		return x.Limit
	}
	return ""
}

type PromptResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Ответ модели
	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	// время, затраченное на генерацию (сек.)
	ProcessingTime float64 `protobuf:"fixed64,2,opt,name=processingTime,proto3" json:"processingTime,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PromptResponse) Reset() {
	*x = PromptResponse{}
	mi := &file_core_service_core_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromptResponse) ProtoMessage() {}

func (x *PromptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_service_core_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromptResponse.ProtoReflect.Descriptor instead.
func (*PromptResponse) Descriptor() ([]byte, []int) {
	return file_core_service_core_service_proto_rawDescGZIP(), []int{1}
}

func (x *PromptResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *PromptResponse) GetProcessingTime() float64 {
	if x != nil {
		return x.ProcessingTime
	}
	return 0
}

type FeedbackRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Оценка пользователя на ответ модели (хорошо/плохо)
	Mark bool `protobuf:"varint,1,opt,name=mark,proto3" json:"mark,omitempty"`
	// Запрос, который отправил пользователь
	Prompt string `protobuf:"bytes,2,opt,name=prompt,proto3" json:"prompt,omitempty"`
	// Ответ модели
	Response      string `protobuf:"bytes,3,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeedbackRequest) Reset() {
	*x = FeedbackRequest{}
	mi := &file_core_service_core_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedbackRequest) ProtoMessage() {}

func (x *FeedbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_service_core_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedbackRequest.ProtoReflect.Descriptor instead.
func (*FeedbackRequest) Descriptor() ([]byte, []int) {
	return file_core_service_core_service_proto_rawDescGZIP(), []int{2}
}

func (x *FeedbackRequest) GetMark() bool {
	if x != nil {
		return x.Mark
	}
	return false
}

func (x *FeedbackRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *FeedbackRequest) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

type FeedbackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeedbackResponse) Reset() {
	*x = FeedbackResponse{}
	mi := &file_core_service_core_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedbackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedbackResponse) ProtoMessage() {}

func (x *FeedbackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_service_core_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedbackResponse.ProtoReflect.Descriptor instead.
func (*FeedbackResponse) Descriptor() ([]byte, []int) {
	return file_core_service_core_service_proto_rawDescGZIP(), []int{3}
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_core_service_core_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_service_core_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_core_service_core_service_proto_rawDescGZIP(), []int{4}
}

type HealthResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ответ сервиса о его состоянии
	Healthy       bool `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_core_service_core_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_service_core_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_core_service_core_service_proto_rawDescGZIP(), []int{5}
}

func (x *HealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

var File_core_service_core_service_proto protoreflect.FileDescriptor

const file_core_service_core_service_proto_rawDesc = "" +
	"\n" +
	"\x1fcore-service/core-service.proto\x12\x03api\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\xa1\x01\n" +
	"\rPromptRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\tR\x05limit:f\x92Ac2a{\"text\": \"Что такое минимальное остовное дерево?\", \"limit\": \"5\"}\"\xba\x01\n" +
	"\x0ePromptResponse\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12&\n" +
	"\x0eprocessingTime\x18\x02 \x01(\x01R\x0eprocessingTime:l\x92Ai2g{\"text\": \"Минимальное остовное дерево — это...\", \"processingTime\": 1.234}\"\x98\x02\n" +
	"\x0fFeedbackRequest\x12\x12\n" +
	"\x04mark\x18\x01 \x01(\bR\x04mark\x12\x16\n" +
	"\x06prompt\x18\x02 \x01(\tR\x06prompt\x12\x1a\n" +
	"\bresponse\x18\x03 \x01(\tR\bresponse:\xbc\x01\x92A\xb8\x012\xb5\x01{\"mark\": true, \"prompt\": \"Что такое минимальное остовное дерево?\", \"response\": \"Минимальное остовное дерево — это...\"}\"\x12\n" +
	"\x10FeedbackResponse\"\x0f\n" +
	"\rHealthRequest\"B\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy:\x16\x92A\x132\x11{\"healthy\": true}2\xb9\x05\n" +
	"\vCoreService\x12\xc0\x01\n" +
	"\x06Prompt\x12\x12.api.PromptRequest\x1a\x13.api.PromptResponse\"\x8c\x01\x92Ap\x12\"Задать вопрос WiseTask\x1aJВозвращает ответ на вопрос пользователя\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/api/v1/prompt\x12\xe5\x01\n" +
	"\bFeedback\x12\x14.api.FeedbackRequest\x1a\x15.api.FeedbackResponse\"\xab\x01\x92A\x8c\x01\x12:Отправить отзыв на ответ модели\x1aNОставляет отзыв на ответ модели на сервере\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/api/v1/feedback\x12\xfe\x01\n" +
	"\vHealthCheck\x12\x12.api.HealthRequest\x1a\x13.api.HealthResponse\"\xc5\x01\x92A\xa6\x01\x12DПроверяет работоспособность сервиса\x1a^Отправляет информацию о работоспособности сервиса\x82\xd3\xe4\x93\x02\x15\x12\x13/api/v1/healthcheckB\n" +
	"Z\bapi/coreb\x06proto3"

var (
	file_core_service_core_service_proto_rawDescOnce sync.Once
	file_core_service_core_service_proto_rawDescData []byte
)

func file_core_service_core_service_proto_rawDescGZIP() []byte {
	file_core_service_core_service_proto_rawDescOnce.Do(func() {
		file_core_service_core_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_service_core_service_proto_rawDesc), len(file_core_service_core_service_proto_rawDesc)))
	})
	return file_core_service_core_service_proto_rawDescData
}

var file_core_service_core_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_core_service_core_service_proto_goTypes = []any{
	(*PromptRequest)(nil),    // 0: api.PromptRequest
	(*PromptResponse)(nil),   // 1: api.PromptResponse
	(*FeedbackRequest)(nil),  // 2: api.FeedbackRequest
	(*FeedbackResponse)(nil), // 3: api.FeedbackResponse
	(*HealthRequest)(nil),    // 4: api.HealthRequest
	(*HealthResponse)(nil),   // 5: api.HealthResponse
}
var file_core_service_core_service_proto_depIdxs = []int32{
	0, // 0: api.CoreService.Prompt:input_type -> api.PromptRequest
	2, // 1: api.CoreService.Feedback:input_type -> api.FeedbackRequest
	4, // 2: api.CoreService.HealthCheck:input_type -> api.HealthRequest
	1, // 3: api.CoreService.Prompt:output_type -> api.PromptResponse
	3, // 4: api.CoreService.Feedback:output_type -> api.FeedbackResponse
	5, // 5: api.CoreService.HealthCheck:output_type -> api.HealthResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_core_service_core_service_proto_init() }
func file_core_service_core_service_proto_init() {
	if File_core_service_core_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_service_core_service_proto_rawDesc), len(file_core_service_core_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_core_service_core_service_proto_goTypes,
		DependencyIndexes: file_core_service_core_service_proto_depIdxs,
		MessageInfos:      file_core_service_core_service_proto_msgTypes,
	}.Build()
	File_core_service_core_service_proto = out.File
	file_core_service_core_service_proto_goTypes = nil
	file_core_service_core_service_proto_depIdxs = nil
}
