// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: llm-service/llm-service.proto

package llm

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenerateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Question      string                 `protobuf:"bytes,1,opt,name=question,proto3" json:"question,omitempty"`
	Contexts      []string               `protobuf:"bytes,2,rep,name=contexts,proto3" json:"contexts,omitempty"`
	RequestId     string                 `protobuf:"bytes,3,opt,name=requestId,proto3" json:"requestId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateRequest) Reset() {
	*x = GenerateRequest{}
	mi := &file_llm_service_llm_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateRequest) ProtoMessage() {}

func (x *GenerateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_llm_service_llm_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateRequest.ProtoReflect.Descriptor instead.
func (*GenerateRequest) Descriptor() ([]byte, []int) {
	return file_llm_service_llm_service_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateRequest) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *GenerateRequest) GetContexts() []string {
	if x != nil {
		return x.Contexts
	}
	return nil
}

func (x *GenerateRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type GenerateResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Answer         string                 `protobuf:"bytes,1,opt,name=answer,proto3" json:"answer,omitempty"`
	ProcessingTime float64                `protobuf:"fixed64,2,opt,name=processingTime,proto3" json:"processingTime,omitempty"`
	ErrorMessage   string                 `protobuf:"bytes,3,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GenerateResponse) Reset() {
	*x = GenerateResponse{}
	mi := &file_llm_service_llm_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateResponse) ProtoMessage() {}

func (x *GenerateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_llm_service_llm_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateResponse.ProtoReflect.Descriptor instead.
func (*GenerateResponse) Descriptor() ([]byte, []int) {
	return file_llm_service_llm_service_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateResponse) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

func (x *GenerateResponse) GetProcessingTime() float64 {
	if x != nil {
		return x.ProcessingTime
	}
	return 0
}

func (x *GenerateResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_llm_service_llm_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_llm_service_llm_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_llm_service_llm_service_proto_rawDescGZIP(), []int{2}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	StatusMessage string                 `protobuf:"bytes,2,opt,name=status_message,json=statusMessage,proto3" json:"status_message,omitempty"`
	ModelLoaded   string                 `protobuf:"bytes,3,opt,name=modelLoaded,proto3" json:"modelLoaded,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_llm_service_llm_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_llm_service_llm_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_llm_service_llm_service_proto_rawDescGZIP(), []int{3}
}

func (x *HealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthResponse) GetStatusMessage() string {
	if x != nil {
		return x.StatusMessage
	}
	return ""
}

func (x *HealthResponse) GetModelLoaded() string {
	if x != nil {
		return x.ModelLoaded
	}
	return ""
}

var File_llm_service_llm_service_proto protoreflect.FileDescriptor

const file_llm_service_llm_service_proto_rawDesc = "" +
	"\n" +
	"\x1dllm-service/llm-service.proto\x12\x03llm\"g\n" +
	"\x0fGenerateRequest\x12\x1a\n" +
	"\bquestion\x18\x01 \x01(\tR\bquestion\x12\x1a\n" +
	"\bcontexts\x18\x02 \x03(\tR\bcontexts\x12\x1c\n" +
	"\trequestId\x18\x03 \x01(\tR\trequestId\"v\n" +
	"\x10GenerateResponse\x12\x16\n" +
	"\x06answer\x18\x01 \x01(\tR\x06answer\x12&\n" +
	"\x0eprocessingTime\x18\x02 \x01(\x01R\x0eprocessingTime\x12\"\n" +
	"\ferrorMessage\x18\x03 \x01(\tR\ferrorMessage\"\x0f\n" +
	"\rHealthRequest\"s\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12%\n" +
	"\x0estatus_message\x18\x02 \x01(\tR\rstatusMessage\x12 \n" +
	"\vmodelLoaded\x18\x03 \x01(\tR\vmodelLoaded2}\n" +
	"\n" +
	"llmService\x127\n" +
	"\bGenerate\x12\x14.llm.GenerateRequest\x1a\x15.llm.GenerateResponse\x126\n" +
	"\vHealthCheck\x12\x12.llm.HealthRequest\x1a\x13.llm.HealthResponseB\tZ\aapi/llmb\x06proto3"

var (
	file_llm_service_llm_service_proto_rawDescOnce sync.Once
	file_llm_service_llm_service_proto_rawDescData []byte
)

func file_llm_service_llm_service_proto_rawDescGZIP() []byte {
	file_llm_service_llm_service_proto_rawDescOnce.Do(func() {
		file_llm_service_llm_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_llm_service_llm_service_proto_rawDesc), len(file_llm_service_llm_service_proto_rawDesc)))
	})
	return file_llm_service_llm_service_proto_rawDescData
}

var file_llm_service_llm_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_llm_service_llm_service_proto_goTypes = []any{
	(*GenerateRequest)(nil),  // 0: llm.GenerateRequest
	(*GenerateResponse)(nil), // 1: llm.GenerateResponse
	(*HealthRequest)(nil),    // 2: llm.HealthRequest
	(*HealthResponse)(nil),   // 3: llm.HealthResponse
}
var file_llm_service_llm_service_proto_depIdxs = []int32{
	0, // 0: llm.llmService.Generate:input_type -> llm.GenerateRequest
	2, // 1: llm.llmService.HealthCheck:input_type -> llm.HealthRequest
	1, // 2: llm.llmService.Generate:output_type -> llm.GenerateResponse
	3, // 3: llm.llmService.HealthCheck:output_type -> llm.HealthResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_llm_service_llm_service_proto_init() }
func file_llm_service_llm_service_proto_init() {
	if File_llm_service_llm_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_llm_service_llm_service_proto_rawDesc), len(file_llm_service_llm_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_llm_service_llm_service_proto_goTypes,
		DependencyIndexes: file_llm_service_llm_service_proto_depIdxs,
		MessageInfos:      file_llm_service_llm_service_proto_msgTypes,
	}.Build()
	File_llm_service_llm_service_proto = out.File
	file_llm_service_llm_service_proto_goTypes = nil
	file_llm_service_llm_service_proto_depIdxs = nil
}
