from __future__ import annotations

import os
from typing import Any

__all__ = [
    "_getenv_bool",
    "_w",
    # core env-driven settings
    "DEFAULT_COLLECTION",
    "VECTOR_SIZE",
    # search defaults
    "DEFAULT_SEARCH_MAX_CHARS",
    "DEFAULT_SEARCH_WITH_CHUNK_TEXT",
    "DEFAULT_SEARCH_INCLUDE_DEBUG",
    "DEFAULT_SEARCH_STITCH_NEIGHBORS",
    "DEFAULT_SEARCH_STITCH_BEFORE",
    "DEFAULT_SEARCH_STITCH_AFTER",
    "DEFAULT_SEARCH_STITCH_USE_CHUNK_TEXT",
    "DEFAULT_SEARCH_LIMIT",
    "SEARCH_INTERNAL_MULT",
    "SEARCH_INTERNAL_MIN",
    "SEARCH_INTERNAL_MAX",
    # weights and thresholds
    "W_VECTOR",
    "W_LEX_MATCH",
    "TH_LEX_MATCH_CAP",
    "W_TITLE_MATCH",
    "W_SOURCE_MATCH",
    "W_APPROX_TITLE_HITS",
    "TH_APPROX_TITLE_HITS_CAP",
    "W_FUZZY_TITLE_HITS",
    "TH_FUZZY_TITLE_CAP",
    "W_FUZZY_TEXT_HITS",
    "TH_FUZZY_TEXT_CAP",
    "W_ALGO_NAME_MATCH",
    "W_DEF_BOOST",
    "W_EXACT_SOURCE_MATCH",
    "W_DEF_LIKE",
    "W_HAS_PROPERTIES",
    "W_HAS_LEMMA_THEOREM",
    "W_BARYCENTER_FOCUS",
    "W_BARY_BONUS",
    "W_BARY_MISS_PENALTY",
    "W_BOILERPLATE_PENALTY",
    "W_EARLY_CHUNK_BONUS",
    "TH_EARLY_CHUNK_INDEX",
    "W_IS_DEFINITION_FLAG",
    "W_HAS_MATH_FLAG",
    "W_ALGO_NAME_PAYLOAD_MATCH",
    "W_IS_ALGORITHM_FLAG",
    "W_TITLE_PHRASE",
    "W_TEXT_PHRASE",
]

def _getenv_bool(name: str, default: bool) -> bool:
    val = os.getenv(name)
    if val is None:
        return default
    return val.strip().lower() in {"1", "true", "yes", "y", "on"}

DEFAULT_COLLECTION: str = os.getenv("COLLECTION_NAME", "latex_books")
VECTOR_SIZE: int = int(os.getenv("VECTOR_SIZE", "384"))

DEFAULT_SEARCH_MAX_CHARS: int = int(os.getenv("SEARCH_MAX_CHARS", "5000"))
DEFAULT_SEARCH_WITH_CHUNK_TEXT: bool = _getenv_bool("SEARCH_WITH_CHUNK_TEXT", False)
DEFAULT_SEARCH_INCLUDE_DEBUG: bool = _getenv_bool("SEARCH_INCLUDE_DEBUG", False)
DEFAULT_SEARCH_STITCH_NEIGHBORS: bool = _getenv_bool("SEARCH_STITCH_NEIGHBORS", True)
DEFAULT_SEARCH_STITCH_BEFORE: int = int(os.getenv("SEARCH_STITCH_BEFORE", "2"))
DEFAULT_SEARCH_STITCH_AFTER: int = int(os.getenv("SEARCH_STITCH_AFTER", "8"))
DEFAULT_SEARCH_STITCH_USE_CHUNK_TEXT: bool = _getenv_bool("SEARCH_STITCH_USE_CHUNK_TEXT", True)
DEFAULT_SEARCH_LIMIT: int = int(os.getenv("SEARCH_DEFAULT_LIMIT", "5"))
SEARCH_INTERNAL_MULT: int = int(os.getenv("SEARCH_INTERNAL_MULT", "18"))
SEARCH_INTERNAL_MIN: int = int(os.getenv("SEARCH_INTERNAL_MIN", "40"))
SEARCH_INTERNAL_MAX: int = int(os.getenv("SEARCH_INTERNAL_MAX", "220"))


def _w(name: str, default: float) -> float:
    try:
        return float(os.getenv(f"WEIGHT_{name}", str(default)))
    except Exception:
        return default

W_VECTOR = _w("VECTOR", 1.0)
W_LEX_MATCH = _w("LEX_MATCH", 0.50)
TH_LEX_MATCH_CAP = int(os.getenv("TH_LEX_MATCH_CAP", "6"))
W_TITLE_MATCH = _w("TITLE_MATCH", 0.90)
W_SOURCE_MATCH = _w("SOURCE_MATCH", 0.40)
W_APPROX_TITLE_HITS = _w("APPROX_TITLE_HITS", 0.55)
TH_APPROX_TITLE_HITS_CAP = int(os.getenv("TH_APPROX_TITLE_HITS_CAP", "3"))
W_FUZZY_TITLE_HITS = _w("FUZZY_TITLE_HITS", 0.60)
TH_FUZZY_TITLE_CAP = int(os.getenv("TH_FUZZY_TITLE_CAP", "2"))
W_FUZZY_TEXT_HITS = _w("FUZZY_TEXT_HITS", 0.35)
TH_FUZZY_TEXT_CAP = int(os.getenv("TH_FUZZY_TEXT_CAP", "3"))
W_ALGO_NAME_MATCH = _w("ALGO_NAME_MATCH", 1.80)
W_DEF_BOOST = _w("DEF_BOOST", 0.70)
W_EXACT_SOURCE_MATCH = _w("EXACT_SOURCE_MATCH", 2.20)
W_DEF_LIKE = _w("DEF_LIKE", 0.90)
W_HAS_PROPERTIES = _w("HAS_PROPERTIES", 0.55)
W_HAS_LEMMA_THEOREM = _w("HAS_LEMMA_THEOREM", 0.35)
W_BARYCENTER_FOCUS = _w("BARYCENTER_FOCUS", 0.60)
W_BARY_BONUS = _w("BARY_BONUS", 3.5)
W_BARY_MISS_PENALTY = _w("BARY_MISS_PENALTY", -2.2)
W_BOILERPLATE_PENALTY = _w("BOILERPLATE_PENALTY", -1.10)
W_EARLY_CHUNK_BONUS = _w("EARLY_CHUNK_BONUS", 0.45)
TH_EARLY_CHUNK_INDEX = int(os.getenv("TH_EARLY_CHUNK_INDEX", "3"))
W_IS_DEFINITION_FLAG = _w("IS_DEFINITION_FLAG", 1.10)
W_HAS_MATH_FLAG = _w("HAS_MATH_FLAG", 0.35)
W_ALGO_NAME_PAYLOAD_MATCH = _w("ALGO_NAME_PAYLOAD_MATCH", 0.60)
W_IS_ALGORITHM_FLAG = _w("IS_ALGORITHM_FLAG", 0.40)
W_TITLE_PHRASE = _w("TITLE_PHRASE", 1.40)
W_TEXT_PHRASE = _w("TEXT_PHRASE", 0.60)
